version: '3.8'
services:
  postgres:
    image: postgres:13.2
    env_file:
      - .development.env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/var/lib/redis

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'

volumes:
  postgres_volume:
  redis_volume:
